// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-trips.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-trips.ts
var list_trips_default = defineTool({
  name: "list_trips",
  title: "List trips",
  description: "List all trips the signed-in user can access (owner or collaborator).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("trips").select("id, title, destination, start_date, end_date, status").order("start_date", { ascending: false, nullsFirst: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { trips: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-trip.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var get_trip_default = defineTool2({
  name: "get_trip",
  title: "Get trip details",
  description: "Fetch a single trip with its days and itinerary items. Use list_trips first to discover trip IDs.",
  inputSchema: {
    trip_id: z.string().uuid().describe("Trip UUID from list_trips")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ trip_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: trip, error: tripErr } = await supabase.from("trips").select("*").eq("id", trip_id).maybeSingle();
    if (tripErr || !trip) {
      return { content: [{ type: "text", text: tripErr?.message ?? "Trip not found" }], isError: true };
    }
    const { data: days } = await supabase.from("trip_days").select("id, day_number, date, title, neighborhood_focus").eq("trip_id", trip_id).order("day_number");
    const dayIds = (days ?? []).map((d) => d.id);
    let items = [];
    if (dayIds.length) {
      const { data } = await supabase.from("itinerary_items").select("id, trip_day_id, title, start_time, end_time, notes, place_id").in("trip_day_id", dayIds);
      items = data ?? [];
    }
    const result = { trip, days: days ?? [], items };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/create-trip.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var create_trip_default = defineTool3({
  name: "create_trip",
  title: "Create trip",
  description: "Create a new trip for the signed-in user. The caller becomes the owner.",
  inputSchema: {
    title: z2.string().trim().min(1).max(200).describe("Trip name"),
    destination: z2.string().trim().min(1).max(200).describe("Destination city or region"),
    start_date: z2.string().date().optional().describe("YYYY-MM-DD start date"),
    end_date: z2.string().date().optional().describe("YYYY-MM-DD end date")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, destination, start_date, end_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("create_trip_with_owner", {
      p_title: title,
      p_destination: destination,
      p_start_date: start_date ?? null,
      p_end_date: end_date ?? null
    });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Created trip: ${JSON.stringify(data)}` }],
      structuredContent: { trip: data }
    };
  }
});

// src/lib/mcp/tools/search-places.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var search_places_default = defineTool4({
  name: "search_places",
  title: "Search saved places",
  description: "Search the shared places catalog by name or neighborhood.",
  inputSchema: {
    query: z3.string().trim().min(1).max(200).describe("Text to match in name or neighborhood"),
    limit: z3.number().int().min(1).max(50).optional().describe("Max results (default 20)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const like = `%${query}%`;
    const { data, error } = await supabase.from("places").select("id, name, category, arrondissement, neighborhood_name, rating").or(`name.ilike.${like},neighborhood_name.ilike.${like}`).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { places: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ixhdadzkztjcdqridqha";
var mcp_default = defineMcp({
  name: "le-voyage-mcp",
  title: "Le Voyage",
  version: "0.1.0",
  instructions: "Tools for Le Voyage, an intelligent travel planner. Use list_trips to see the user's trips, get_trip for full itinerary details, create_trip to start a new trip, and search_places to browse the saved places catalog.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_trips_default, get_trip_default, create_trip_default, search_places_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
